package smv.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import java.util.Map;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.IScope;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class WordConstant_Constraints extends BaseConstraintsDescriptor {
  public WordConstant_Constraints() {
    super("smv.structure.WordConstant");
  }

  @Override
  protected Map<String, PropertyConstraintsDescriptor> getNotDefaultProperties() {
    Map<String, PropertyConstraintsDescriptor> properties = new HashMap();
    properties.put("representation", new BasePropertyConstraintsDescriptor("representation", this) {
      @Override
      public boolean hasOwnValidator() {
        return true;
      }

      @Override
      public boolean validateValue(SNode node, String propertyValue, IScope scope) {
        String propertyName = "representation";
        {
          boolean isValid = true;
          isValid = isValid && ConstraintUtil.wordConstantCheckRegexp((SPropertyOperations.getString(propertyValue)));
          Integer l = ConstraintUtil.wordConstantLength((SPropertyOperations.getString(propertyValue)));
          isValid = isValid && !(l != null && l <= 0);
          isValid = isValid && !(ConstraintUtil.wordConstantIsDecimal((SPropertyOperations.getString(propertyValue))) && l == null);
          String value = ConstraintUtil.wordConstantValue((SPropertyOperations.getString(propertyValue)));
          switch (ConstraintUtil.wordConstantBase((SPropertyOperations.getString(propertyValue)))) {
            case 'b':
              isValid = isValid && value.matches("[]");
            default:
              return false;
          }
          // TODO: check base etc 
          return isVali;
        }
      }
    });
    return properties;
  }
}
