package statechart.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.textGen.TextGenManager;

public class BlockStatement_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    if (ListSequence.fromList(SLinkOperations.getTargets(node, "statements", true)).isNotEmpty()) {
      for (SNode item : SLinkOperations.getTargets(node, "statements", true)) {
        TextGenManager.instance().appendNodeText(this.getContext(), this.getBuffer(), item, this.getSNode());
      }
    }
  }
}
