package statechart.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.textGen.TextGenManager;

public class Scheme_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    this.append("import StateChart");
    this.appendNewLine();
    this.append("import Data.Graph.Inductive.Graph");
    this.appendNewLine();
    this.append("import Promela");
    this.appendNewLine();
    this.increaseDepth();
    if (ListSequence.fromList(SLinkOperations.getTargets(node, "actors", true)).isNotEmpty()) {
      for (SNode item : SLinkOperations.getTargets(node, "actors", true)) {
        TextGenManager.instance().appendNodeText(this.getContext(), this.getBuffer(), item, this.getSNode());
      }
    }
    this.decreaseDepth();
  }

  public String getExtension(SNode node) {
    return "hs";
  }
}
