package statechart.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.textGen.TextGenManager;

public class Statechart_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    this.append("Machine $ mkGraph [");
    this.increaseDepth();
    this.appendNewLine();
    if (ListSequence.fromList(SLinkOperations.getTargets(node, "states", true)).isNotEmpty()) {
      for (SNode item : SLinkOperations.getTargets(node, "states", true)) {
        TextGenManager.instance().appendNodeText(this.getContext(), this.getBuffer(), item, this.getSNode());
      }
    }
    this.decreaseDepth();
    this.append("] [");
    this.increaseDepth();
    this.appendNewLine();
    if (ListSequence.fromList(SLinkOperations.getTargets(node, "transitions", true)).isNotEmpty()) {
      for (SNode item : SLinkOperations.getTargets(node, "transitions", true)) {
        TextGenManager.instance().appendNodeText(this.getContext(), this.getBuffer(), item, this.getSNode());
      }
    }
    this.decreaseDepth();
    this.append("]");

  }
}
