package statechart.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.textGen.TextGenManager;

public class TargetReference_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    /*
      if (SLinkOperations.getTarget(node, "", false) != null) {
        this.append(Integer.toString(SNodeOperations.getIndexInParent(SLinkOperations.getTarget(SLinkOperations.getTarget(node, "", false), "state", false))));
        if (SLinkOperations.getTarget(SLinkOperations.getTarget(node, "", false), "", false) != null) {
          this.append(", ");
        }
        TextGenManager.instance().appendNodeText(this.getContext(), this.getBuffer(), SLinkOperations.getTarget(node, "", false), this.getSNode());
      }
    */
    this.append(Integer.toString(SNodeOperations.getIndexInParent(SLinkOperations.getTarget(node, "state", false))));
  }
}
