package statechart.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import jetbrains.mps.smodel.SNode;

public class True_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    this.append("GTrue");
  }
}
