package statechart.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import org.jetbrains.mps.openapi.model.SNode;

public class True_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    this.append("GTrue");
  }
}
