package smv.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntention;
import jetbrains.mps.intentions.Intention;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class SetSigned_Intention extends BaseIntention implements Intention {
  public SetSigned_Intention() {
  }

  public String getConcept() {
    return "smv.structure.WordType";
  }

  public boolean isParameterized() {
    return false;
  }

  public boolean isErrorIntention() {
    return false;
  }

  public boolean isAvailableInChildNodes() {
    return false;
  }

  public String getDescription(final SNode node, final EditorContext editorContext) {
    return (SPropertyOperations.getBoolean(node, "isSigned") ?
      "Set 'unsigned'" :
      "Set 'signed'"
    );
  }

  public void execute(final SNode node, final EditorContext editorContext) {
    SPropertyOperations.set(node, "isSigned", "" + (!(SPropertyOperations.getBoolean(node, "isSigned"))));
  }

  public String getLocationString() {
    return "smv.intentions";
  }
}
