package smv.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.language.SConcept;

public class AndExpression_BehaviorDescriptor extends BinaryOperation_BehaviorDescriptor {
  public AndExpression_BehaviorDescriptor() {
  }

  public int virtual_getPriority_1955678301118834003(SConcept thisConcept) {
    return AndExpression_Behavior.virtual_getPriority_1955678301118834003(thisConcept);
  }

  @Override
  public String getConceptFqName() {
    return "smv.structure.AndExpression";
  }
}
