package smv.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  private static String[] stringSwitchCases_846f5o_a0a0a = new String[]{"smv.structure.BooleanConstant", "smv.structure.BooleanType", "smv.structure.IntegerConstant", "smv.structure.SymbolicConstant", "smv.structure.UnspecifiedConcept", "smv.structure.WordConstant", "smv.structure.WordType"};

  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0a, fqName)) {
      case 1:
        return new BooleanType_BehaviorDescriptor();
      case 6:
        return new WordType_BehaviorDescriptor();
      case 4:
        return new UnspecifiedConcept_BehaviorDescriptor();
      case 2:
        return new IntegerConstant_BehaviorDescriptor();
      case 3:
        return new SymbolicConstant_BehaviorDescriptor();
      case 0:
        return new BooleanConstant_BehaviorDescriptor();
      case 5:
        return new WordConstant_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }
}
