package smv.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public class BinaryOperation_Behavior {
  public static void init(SNode thisNode) {
  }

  public static int virtual_getPriority_1955678301118834003(SAbstractConcept thisConcept) {
    return 0;
  }
}
