package smv.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.language.SConcept;

public abstract class BinaryOperation_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public BinaryOperation_BehaviorDescriptor() {
  }

  public int virtual_getPriority_1955678301118834003(SConcept thisConcept) {
    return BinaryOperation_Behavior.virtual_getPriority_1955678301118834003(thisConcept);
  }

  @Override
  public String getConceptFqName() {
    return "smv.structure.BinaryOperation";
  }
}
