package smv.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class BooleanConstant_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public BooleanConstant_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "smv.structure.BooleanConstant";
  }
}
