package smv.behavior;

/*Generated by MPS */


public abstract class CallLikeSingleArgExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public CallLikeSingleArgExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "smv.structure.CallLikeSingleArgExpression";
  }
}
