package smv.behavior;

/*Generated by MPS */


public abstract class CallLikeDoubleArgExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public CallLikeDoubleArgExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "smv.structure.CallLikeDoubleArgExpression";
  }
}
