package smv.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class CaseItem_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public CaseItem_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "smv.structure.CaseItem";
  }
}
