package smv.behavior;

/*Generated by MPS */


public class CaseExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public CaseExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "smv.structure.CaseExpression";
  }
}
