package smv.behavior;

/*Generated by MPS */


public abstract class Constant_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public Constant_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "smv.structure.Constant";
  }
}
