package smv.behavior;

/*Generated by MPS */


public class EnumerationType_BehaviorDescriptor extends SimpleType_BehaviorDescriptor {
  public EnumerationType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "smv.structure.EnumerationType";
  }
}
