package smv.behavior;

/*Generated by MPS */


public class EqExpression_BehaviorDescriptor extends BinaryOperation_BehaviorDescriptor {
  public EqExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "smv.structure.EqExpression";
  }
}
