package smv.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class Expression_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Expression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "smv.structure.Expression";
  }
}
