package smv.behavior;

/*Generated by MPS */


public class InExpression_BehaviorDescriptor extends BinaryOperation_BehaviorDescriptor {
  public InExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "smv.structure.InExpression";
  }
}
