package smv.behavior;

/*Generated by MPS */


public class InitExpression_BehaviorDescriptor extends UnaryExpression_BehaviorDescriptor {
  public InitExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "smv.structure.InitExpression";
  }
}
