package smv.behavior;

/*Generated by MPS */


public class IntegerConstant_BehaviorDescriptor extends UnspecifiedConcept_BehaviorDescriptor implements IConstant_BehaviorDescriptor, IIntegerLiteral_BehaviorDescriptor {
  public IntegerConstant_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "smv.structure.IntegerConstant";
  }
}
