package smv.behavior;

/*Generated by MPS */


public class IntegerConstant_BehaviorDescriptor extends Constant_BehaviorDescriptor implements IEnumerationTypeItem_BehaviorDescriptor {
  public IntegerConstant_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "smv.structure.IntegerConstant";
  }
}
