package smv.behavior;

/*Generated by MPS */


public class NextExpression_BehaviorDescriptor extends UnaryExpression_BehaviorDescriptor {
  public NextExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "smv.structure.NextExpression";
  }
}
