package smv.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public class NotExpression_Behavior {
  public static void init(SNode thisNode) {
  }

  public static int virtual_getPriority_1955678301118834386(SAbstractConcept thisConcept) {
    return -2;
  }
}
