package smv.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.language.SConcept;

public class NotExpression_BehaviorDescriptor extends UnaryExpression_BehaviorDescriptor {
  public NotExpression_BehaviorDescriptor() {
  }

  public int virtual_getPriority_1955678301118834386(SConcept thisConcept) {
    return NotExpression_Behavior.virtual_getPriority_1955678301118834386(thisConcept);
  }

  @Override
  public String getConceptFqName() {
    return "smv.structure.NotExpression";
  }
}
