package smv.behavior;

/*Generated by MPS */


public class ParenthesizedExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public ParenthesizedExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "smv.structure.ParenthesizedExpression";
  }
}
