package smv.behavior;

/*Generated by MPS */


public abstract class PrimitiveType_BehaviorDescriptor extends SimpleType_BehaviorDescriptor {
  public PrimitiveType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "smv.structure.PrimitiveType";
  }
}
