package smv.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class PrimitiveType_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public PrimitiveType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "smv.structure.PrimitiveType";
  }
}
