package smv.behavior;

/*Generated by MPS */


public class ReferenceExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public ReferenceExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "smv.structure.ReferenceExpression";
  }
}
