package smv.behavior;

/*Generated by MPS */


public class SetExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public SetExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "smv.structure.SetExpression";
  }
}
