package smv.behavior;

/*Generated by MPS */


public abstract class SimpleType_BehaviorDescriptor extends Type_BehaviorDescriptor {
  public SimpleType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "smv.structure.SimpleType";
  }
}
