package smv.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.language.SConcept;

public abstract class UnaryExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public UnaryExpression_BehaviorDescriptor() {
  }

  public int virtual_getPriority_1955678301118834386(SConcept thisConcept) {
    return UnaryExpression_Behavior.virtual_getPriority_1955678301118834386(thisConcept);
  }

  @Override
  public String getConceptFqName() {
    return "smv.structure.UnaryExpression";
  }
}
