package smv.behavior;

/*Generated by MPS */


public class UnionExpression_BehaviorDescriptor extends BinaryOperation_BehaviorDescriptor {
  public UnionExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "smv.structure.UnionExpression";
  }
}
