package smv.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class UnspecifiedConcept_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public UnspecifiedConcept_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "smv.structure.UnspecifiedConcept";
  }
}
