package smv.behavior;

/*Generated by MPS */


public class VariableDeclaration_BehaviorDescriptor extends Declaration_BehaviorDescriptor {
  public VariableDeclaration_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "smv.structure.VariableDeclaration";
  }
}
