package smv.behavior;

/*Generated by MPS */


public class Word1Expression_BehaviorDescriptor extends BinaryOperation_BehaviorDescriptor {
  public Word1Expression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "smv.structure.Word1Expression";
  }
}
