package smv.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class WordConstant_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public WordConstant_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "smv.structure.WordConstant";
  }
}
