package smv.behavior;

/*Generated by MPS */


public class WordConstant_BehaviorDescriptor extends Constant_BehaviorDescriptor {
  public WordConstant_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "smv.structure.WordConstant";
  }
}
