package smv.behavior;

/*Generated by MPS */


public class WordType_BehaviorDescriptor extends PrimitiveType_BehaviorDescriptor {
  public WordType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "smv.structure.WordType";
  }
}
