package statechart.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class BlockStatement_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IStatement_BehaviorDescriptor {
  public BlockStatement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "statechart.structure.BlockStatement";
  }
}
