package statechart.behavior;

/*Generated by MPS */


public class BooleanType_BehaviorDescriptor extends PrimitiveType_BehaviorDescriptor {
  public BooleanType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "statechart.structure.BooleanType";
  }
}
