package statechart.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class EmptyStatement_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IStatement_BehaviorDescriptor {
  public EmptyStatement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "statechart.structure.EmptyStatement";
  }
}
