package statechart.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;

public interface IValidIdentifier_BehaviorDescriptor extends INamedConcept_BehaviorDescriptor {
}
