package statechart.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class PrimitiveType_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public PrimitiveType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "statechart.structure.PrimitiveType";
  }
}
