package statechart.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Scheme_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Scheme_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "statechart.structure.Scheme";
  }
}
