package statechart.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class StatechartReference_BehaviorDescriptor extends StatechartExpression_BehaviorDescriptor {
  public StatechartReference_BehaviorDescriptor() {
  }

  public SNode virtual_getStatechart_1955678301119453888(SNode thisNode) {
    return StatechartReference_Behavior.virtual_getStatechart_1955678301119453888(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "statechart.structure.StatechartReference";
  }
}
