package statechart.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public abstract class StatechartExpression_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public StatechartExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "statechart.structure.StatechartExpression";
  }

  public abstract SNode virtual_getStatechart_1955678301119453888(SNode thisNode);
}
