package statechart.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class StatechartReference_Behavior {
  public static void init(SNode thisNode) {
  }

  public static SNode virtual_getStatechart_1955678301119453888(SNode thisNode) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(thisNode, "declaration", false), "body", true);
  }
}
