package statechart.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.ScopeProvider_BehaviorDescriptor;
import jetbrains.mps.scope.Scope;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.core.behavior.ScopeProvider_Behavior;

public class Statechart_BehaviorDescriptor extends StatechartExpression_BehaviorDescriptor implements ScopeProvider_BehaviorDescriptor {
  public Statechart_BehaviorDescriptor() {
  }

  public Scope virtual_getScope_3734116213129936182(SNode thisNode, SNode kind, SNode child) {
    return Statechart_Behavior.virtual_getScope_3734116213129936182(thisNode, kind, child);
  }

  public Scope virtual_getScope_7722139651431880752(SNode thisNode, SNode kind, String role, int index) {
    return ScopeProvider_Behavior.virtual_getScope_7722139651431880752(thisNode, kind, role, index);
  }

  public SNode virtual_getStatechart_1955678301119453888(SNode thisNode) {
    return Statechart_Behavior.virtual_getStatechart_1955678301119453888(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "statechart.structure.Statechart";
  }
}
