package statechart.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import jetbrains.mps.smodel.language.ConceptRegistry;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.behaviour.BehaviorManager;

public class StatechartExpression_Behavior {
  private static Class[] PARAMETERS_2164628666946508700 = {SNode.class};

  public static void init(SNode thisNode) {
  }

  public static SNode virtual_getStatechart_2164628666946508700(SNode thisNode) {
    return null;
  }

  public static SNode call_getStatechart_2164628666946508700(SNode thisNode) {
    BehaviorDescriptor descriptor = ConceptRegistry.getInstance().getBehaviorDescriptorForInstanceNode(thisNode);
    return (SNode) descriptor.invoke(Object.class, SNodeOperations.cast(thisNode, "statechart.structure.StatechartExpression"), "virtual_getStatechart_2164628666946508700", PARAMETERS_2164628666946508700, new Object[]{});
  }

  public static SNode callSuper_getStatechart_2164628666946508700(SNode thisNode, String callerConceptFqName) {
    return (SNode) BehaviorManager.getInstance().invokeSuper(Object.class, SNodeOperations.cast(thisNode, "statechart.structure.StatechartExpression"), callerConceptFqName, "virtual_getStatechart_2164628666946508700", PARAMETERS_2164628666946508700, new Object[]{});
  }
}
