package statechart.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.smodel.behaviour.BehaviorManager;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class StatechartExpression_Behavior {
  public static void init(SNode thisNode) {
  }

  @Deprecated
  public static SNode call_getStatechart_1955678301119453888(SNode thisNode) {
    return BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), thisNode, "virtual_getStatechart_1955678301119453888", new Object[]{});
  }

  @Deprecated
  public static SNode callSuper_getStatechart_1955678301119453888(SNode thisNode, String callerConceptFqName) {
    return BehaviorManager.getInstance().invokeSuper((Class<SNode>) ((Class) Object.class), SNodeOperations.cast(thisNode, "statechart.structure.StatechartExpression"), callerConceptFqName, "virtual_getStatechart_1955678301119453888", new Class[]{SNode.class}, new Object[]{});
  }
}
