package statechart.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public class StatechartReference_BehaviorDescriptor extends StatechartExpression_BehaviorDescriptor {
  public StatechartReference_BehaviorDescriptor() {
  }

  public SNode virtual_getStatechart_2164628666946508700(SNode thisNode) {
    return StatechartReference_Behavior.virtual_getStatechart_2164628666946508700(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "statechart.structure.StatechartReference";
  }
}
