package statechart.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class StatechartReference_Behavior {
  public static void init(SNode thisNode) {
  }

  public static SNode virtual_getStatechart_2164628666946508700(SNode thisNode) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(thisNode, "declaration", false), "body", true);
  }
}
