package statechart.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.scope.SimpleRoleScope;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import jetbrains.mps.internal.collections.runtime.ITranslator2;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class Statechart_Behavior {
  public static void init(SNode thisNode) {
  }

  public static Scope virtual_getScope_3734116213129936182(SNode thisNode, SNode kind, SNode child) {
    if (SConceptOperations.isSubConceptOf(kind, "statechart.structure.State")) {
      return SimpleRoleScope.forNamedElements(thisNode, SLinkOperations.findLinkDeclaration("statechart.structure.Statechart", "states"));
    }
    return null;
  }

  public static List<SNode> call_mySimpleStates_2747754268221231852(SNode thisNode) {
    return ListSequence.fromList(SLinkOperations.getTargets(thisNode, "states", true)).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SLinkOperations.getTarget(it, "structure", true) == null;
      }
    }).toListSequence();
  }

  public static List<SNode> call_myComplexStates_2747754268221231933(SNode thisNode) {
    return ListSequence.fromList(SLinkOperations.getTargets(thisNode, "states", true)).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SLinkOperations.getTarget(it, "structure", true) != null;
      }
    }).toListSequence();
  }

  public static List<SNode> call_simpleStates_2747754268221231605(SNode thisNode) {
    return ListSequence.fromList(Statechart_Behavior.call_mySimpleStates_2747754268221231852(thisNode)).concat(ListSequence.fromList(Statechart_Behavior.call_myComplexStates_2747754268221231933(thisNode)).translate(new ITranslator2<SNode, SNode>() {
      public Iterable<SNode> translate(SNode it) {
        return Statechart_Behavior.call_simpleStates_2747754268221231605(BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), SLinkOperations.getTarget(it, "structure", true), "virtual_getStatechart_1955678301119453888", new Object[]{}));
      }
    })).toListSequence();
  }

  public static List<SNode> call_complexStates_2747754268221235094(SNode thisNode) {
    return ListSequence.fromList(Statechart_Behavior.call_myComplexStates_2747754268221231933(thisNode)).concat(ListSequence.fromList(Statechart_Behavior.call_myComplexStates_2747754268221231933(thisNode)).translate(new ITranslator2<SNode, SNode>() {
      public Iterable<SNode> translate(SNode it) {
        return Statechart_Behavior.call_complexStates_2747754268221235094(BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), SLinkOperations.getTarget(it, "structure", true), "virtual_getStatechart_1955678301119453888", new Object[]{}));
      }
    })).toListSequence();
  }

  public static List<SNode> call_myInitialStates_2747754268221309465(SNode thisNode) {
    return ListSequence.fromList(SLinkOperations.getTargets(thisNode, "states", true)).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SPropertyOperations.getBoolean(it, "isInitial");
      }
    }).toListSequence();
  }

  public static List<SNode> call_myFinalStates_2747754268221309491(SNode thisNode) {
    return ListSequence.fromList(SLinkOperations.getTargets(thisNode, "states", true)).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SPropertyOperations.getBoolean(it, "isFinal");
      }
    }).toListSequence();
  }

  public static SNode call_mySingleInitial_2747754268221309519(SNode thisNode) {
    List<SNode> mfs = Statechart_Behavior.call_myInitialStates_2747754268221309465(thisNode);
    if ((int) ListSequence.fromList(mfs).count() == 1) {
      return ListSequence.fromList(mfs).getElement(0);
    } else {
      return null;
    }
  }

  public static SNode call_mySingleFinal_2747754268221309668(SNode thisNode) {
    List<SNode> mfs = Statechart_Behavior.call_myFinalStates_2747754268221309491(thisNode);
    if ((int) ListSequence.fromList(mfs).count() == 1) {
      return ListSequence.fromList(mfs).getElement(0);
    } else {
      return null;
    }
  }

  public static SNode call_singleInitial_2747754268221309514(SNode thisNode) {
    SNode msf = Statechart_Behavior.call_mySingleInitial_2747754268221309519(thisNode);
    return (msf == null ?
      null :
      (SLinkOperations.getTarget(msf, "structure", true) == null ?
        msf :
        Statechart_Behavior.call_singleInitial_2747754268221309514(BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), SLinkOperations.getTarget(msf, "structure", true), "virtual_getStatechart_1955678301119453888", new Object[]{}))
      )
    );
  }

  public static SNode call_singleFinal_2747754268221309910(SNode thisNode) {
    SNode msf = Statechart_Behavior.call_mySingleFinal_2747754268221309668(thisNode);
    return (msf == null ?
      null :
      (SLinkOperations.getTarget(msf, "structure", true) == null ?
        msf :
        Statechart_Behavior.call_singleFinal_2747754268221309910(BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), SLinkOperations.getTarget(msf, "structure", true), "virtual_getStatechart_1955678301119453888", new Object[]{}))
      )
    );
  }

  public static SNode virtual_getStatechart_1955678301119453888(SNode thisNode) {
    return thisNode;
  }
}
