package statechart.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import jetbrains.mps.smodel.SNode;

public abstract class StatechartExpression_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public StatechartExpression_BehaviorDescriptor() {
  }

  public SNode virtual_getStatechart_2164628666946508700(SNode thisNode) {
    return StatechartExpression_Behavior.virtual_getStatechart_2164628666946508700(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "statechart.structure.StatechartExpression";
  }
}
