package statechart.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.scope.Scope;

public class TargetReference_BehaviorDescriptor extends TargetRefExpression_BehaviorDescriptor {
  public TargetReference_BehaviorDescriptor() {
  }

  public SNode virtual_getEndPointState_2164628666946425581(SNode thisNode) {
    return TargetReference_Behavior.virtual_getEndPointState_2164628666946425581(thisNode);
  }

  public Scope virtual_getTargetRefScope_3233011721676204377(SNode thisNode, SNode kind, SNode child) {
    return TargetReference_Behavior.virtual_getTargetRefScope_3233011721676204377(thisNode, kind, child);
  }

  public boolean virtual_isEndPoint_2164628666946456298(SNode thisNode) {
    return TargetReference_Behavior.virtual_isEndPoint_2164628666946456298(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "statechart.structure.TargetReference";
  }
}
