package statechart.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.scope.EmptyScope;
import jetbrains.mps.lang.core.behavior.ScopeProvider_Behavior;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class TargetReference_Behavior {
  public static void init(SNode thisNode) {
  }

  public static Scope virtual_getTargetRefScope_3233011721676204377(SNode thisNode, SNode kind, SNode child) {
    if (SLinkOperations.getTarget(SLinkOperations.getTarget(thisNode, "state", false), "structure", true) == null) {
      return new EmptyScope();
    } else {
      return ScopeProvider_Behavior.call_getScope_3734116213129936182(StatechartExpression_Behavior.call_getStatechart_2164628666946508700(SLinkOperations.getTarget(SNodeOperations.cast(SLinkOperations.getTarget(thisNode, "state", false), "statechart.structure.State"), "structure", true)), kind, child);
    }
  }

  public static SNode virtual_getEndPointState_2164628666946425581(SNode thisNode) {
    if (SLinkOperations.getTarget(SLinkOperations.getTarget(thisNode, "state", false), "structure", true) == null) {
      return SLinkOperations.getTarget(thisNode, "state", false);
    } else {
      return (TargetRefExpression_Behavior.call_toFinal_2747754268221296052(thisNode) ?
        Statechart_Behavior.call_singleFinal_2747754268221309910(StatechartExpression_Behavior.call_getStatechart_2164628666946508700(SLinkOperations.getTarget(SNodeOperations.cast(SLinkOperations.getTarget(thisNode, "state", false), "statechart.structure.State"), "structure", true))) :
        Statechart_Behavior.call_singleInitial_2747754268221309514(StatechartExpression_Behavior.call_getStatechart_2164628666946508700(SLinkOperations.getTarget(SNodeOperations.cast(SLinkOperations.getTarget(thisNode, "state", false), "statechart.structure.State"), "structure", true)))
      );
    }
  }

  public static boolean virtual_isEndPoint_2164628666946456298(SNode thisNode) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(thisNode, "state", false), "structure", true) == null;
  }
}
