package statechart.behavior;

/*Generated by MPS */

import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.SNode;

public class TargetReference_BehaviorDescriptor extends TargetRefExpression_BehaviorDescriptor {
  public TargetReference_BehaviorDescriptor() {
  }

  public Scope virtual_getTargetRefScope_3233011721676204377(SNode thisNode, SNode kind, SNode child) {
    return TargetReference_Behavior.virtual_getTargetRefScope_3233011721676204377(thisNode, kind, child);
  }

  @Override
  public String getConceptFqName() {
    return "statechart.structure.TargetReference";
  }
}
