package statechart.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.scope.Scope;

public class TargetReference_BehaviorDescriptor extends TargetRefExpression_BehaviorDescriptor {
  public TargetReference_BehaviorDescriptor() {
  }

  public SNode virtual_getEndPointState_1955678301119751738(SNode thisNode) {
    return TargetReference_Behavior.virtual_getEndPointState_1955678301119751738(thisNode);
  }

  public Scope virtual_getTargetRefScope_3233011721676204377(SNode thisNode, SNode kind, SNode child) {
    return TargetReference_Behavior.virtual_getTargetRefScope_3233011721676204377(thisNode, kind, child);
  }

  public boolean virtual_isEndPoint_1955678301119752454(SNode thisNode) {
    return TargetReference_Behavior.virtual_isEndPoint_1955678301119752454(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "statechart.structure.TargetReference";
  }
}
