package statechart.behavior;

/*Generated by MPS */


public class TargetRefDotExpression_BehaviorDescriptor extends TargetReference_BehaviorDescriptor {
  public TargetRefDotExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "statechart.structure.TargetRefDotExpression";
  }
}
