package statechart.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class TargetReferenceType_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public TargetReferenceType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "statechart.structure.TargetReferenceType";
  }
}
