package statechart.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.lang.scopes.runtime.ScopeUtils;
import jetbrains.mps.lang.core.behavior.ScopeProvider_Behavior;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class TargetRefDotExpression_Behavior {
  public static void init(SNode thisNode) {
  }

  public static Scope virtual_getScope_3734116213129936182(SNode thisNode, SNode kind, SNode child) {
    if (ScopeUtils.comeFrom("left", thisNode, child)) {
      return ScopeProvider_Behavior.call_getScope_3734116213129936182(SNodeOperations.getAncestor(thisNode, "jetbrains.mps.lang.core.structure.ScopeProvider", false, false), kind, child);
    } else {
      return TargetRefExpression_Behavior.call_getTargetRefScope_3233011721676204377(SLinkOperations.getTarget(thisNode, "left", true), kind, child);
    }
  }

  public static Scope virtual_getTargetRefScope_3233011721676204377(SNode thisNode, SNode kind, SNode child) {
    return ScopeProvider_Behavior.call_getScope_3734116213129936182(thisNode, kind, child);
  }
}
