package statechart.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.smodel.behaviour.BehaviorManager;

public class TargetRefExpression_Behavior {
  public static void init(SNode thisNode) {
  }

  public static boolean call_toFinal_2747754268221296052(SNode thisNode) {
    if (SNodeOperations.hasRole(thisNode, "statechart.structure.Transition", "from")) {
      return true;
    }
    if (SNodeOperations.hasRole(thisNode, "statechart.structure.Transition", "to")) {
      return false;
    }
    if (SNodeOperations.hasRole(thisNode, "statechart.structure.TargetRefDotExpression", "left") || SNodeOperations.hasRole(thisNode, "statechart.structure.TargetRefDotExpression", "right")) {
      return TargetRefExpression_Behavior.call_toFinal_2747754268221296052(((SNode) SNodeOperations.getParent(thisNode)));
    }
    // todo: why assertion fails ? 
    /*
      assert false;
    */
    return false;
  }

  @Deprecated
  public static Scope call_getTargetRefScope_3233011721676204377(SNode thisNode, SNode kind, SNode child) {
    return BehaviorReflection.invokeVirtual(Scope.class, thisNode, "virtual_getTargetRefScope_3233011721676204377", new Object[]{kind, child});
  }

  @Deprecated
  public static SNode call_getEndPointState_1955678301119751738(SNode thisNode) {
    return BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), thisNode, "virtual_getEndPointState_1955678301119751738", new Object[]{});
  }

  @Deprecated
  public static boolean call_isEndPoint_1955678301119752454(SNode thisNode) {
    return BehaviorReflection.invokeVirtual(Boolean.TYPE, thisNode, "virtual_isEndPoint_1955678301119752454", new Object[]{});
  }

  @Deprecated
  public static Scope callSuper_getTargetRefScope_3233011721676204377(SNode thisNode, String callerConceptFqName, SNode kind, SNode child) {
    return BehaviorManager.getInstance().invokeSuper(Scope.class, SNodeOperations.cast(thisNode, "statechart.structure.TargetRefExpression"), callerConceptFqName, "virtual_getTargetRefScope_3233011721676204377", new Class[]{SNode.class, SNode.class, SNode.class}, new Object[]{kind, child});
  }

  @Deprecated
  public static SNode callSuper_getEndPointState_1955678301119751738(SNode thisNode, String callerConceptFqName) {
    return BehaviorManager.getInstance().invokeSuper((Class<SNode>) ((Class) Object.class), SNodeOperations.cast(thisNode, "statechart.structure.TargetRefExpression"), callerConceptFqName, "virtual_getEndPointState_1955678301119751738", new Class[]{SNode.class}, new Object[]{});
  }

  @Deprecated
  public static boolean callSuper_isEndPoint_1955678301119752454(SNode thisNode, String callerConceptFqName) {
    return BehaviorManager.getInstance().invokeSuper(Boolean.TYPE, SNodeOperations.cast(thisNode, "statechart.structure.TargetRefExpression"), callerConceptFqName, "virtual_isEndPoint_1955678301119752454", new Class[]{SNode.class}, new Object[]{});
  }
}
