package statechart.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.scope.EmptyScope;
import jetbrains.mps.lang.core.behavior.ScopeProvider_Behavior;

public class TargetReference_Behavior {
  public static void init(SNode thisNode) {
  }

  public static Scope virtual_getTargetRefScope_3233011721676204377(SNode thisNode, SNode kind, SNode child) {
    if (SLinkOperations.getTarget(SLinkOperations.getTarget(thisNode, "state", false), "structure", true) == null) {
      return new EmptyScope();
    } else {
      return ScopeProvider_Behavior.call_getScope_3734116213129936182(SLinkOperations.getTarget(SLinkOperations.getTarget(thisNode, "state", false), "structure", true), kind, child);
    }
  }
}
