package statechart.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.lang.scopes.runtime.ScopeUtils;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class TargetRefDotExpression_Behavior {
  public static void init(SNode thisNode) {
  }

  public static Scope virtual_getScope_3734116213129936182(SNode thisNode, SNode kind, SNode child) {
    if (ScopeUtils.comeFrom("left", thisNode, child)) {
      return BehaviorReflection.invokeVirtual(Scope.class, SNodeOperations.getAncestor(thisNode, "jetbrains.mps.lang.core.structure.ScopeProvider", false, false), "virtual_getScope_3734116213129936182", new Object[]{kind, child});
    } else {
      return BehaviorReflection.invokeVirtual(Scope.class, SLinkOperations.getTarget(thisNode, "left", true), "virtual_getTargetRefScope_3233011721676204377", new Object[]{kind, child});
    }
  }

  public static Scope virtual_getTargetRefScope_3233011721676204377(SNode thisNode, SNode kind, SNode child) {
    return BehaviorReflection.invokeVirtual(Scope.class, thisNode, "virtual_getScope_3734116213129936182", new Object[]{kind, child});
  }

  public static SNode virtual_getEndPointState_1955678301119751738(SNode thisNode) {
    return BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), SLinkOperations.getTarget(thisNode, "right", true), "virtual_getEndPointState_1955678301119751738", new Object[]{});
  }

  public static boolean virtual_isEndPoint_1955678301119752454(SNode thisNode) {
    return false;
  }
}
