package statechart.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.scope.EmptyScope;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;

public class TargetReference_Behavior {
  public static void init(SNode thisNode) {
  }

  public static Scope virtual_getTargetRefScope_3233011721676204377(SNode thisNode, SNode kind, SNode child) {
    if (SLinkOperations.getTarget(SLinkOperations.getTarget(thisNode, "state", false), "structure", true) == null) {
      return new EmptyScope();
    } else {
      return BehaviorReflection.invokeVirtual(Scope.class, SLinkOperations.getTarget(SLinkOperations.getTarget(thisNode, "state", false), "structure", true), "virtual_getScope_3734116213129936182", new Object[]{kind, child});
    }
  }

  public static SNode virtual_getEndPointState_1955678301119751738(SNode thisNode) {
    if (SLinkOperations.getTarget(SLinkOperations.getTarget(thisNode, "state", false), "structure", true) == null) {
      return SLinkOperations.getTarget(thisNode, "state", false);
    } else {
      return (TargetRefExpression_Behavior.call_toFinal_2747754268221296052(thisNode) ?
        Statechart_Behavior.call_singleFinal_2747754268221309910(BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), SLinkOperations.getTarget(SLinkOperations.getTarget(thisNode, "state", false), "structure", true), "virtual_getStatechart_1955678301119453888", new Object[]{})) :
        Statechart_Behavior.call_singleInitial_2747754268221309514(BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), SLinkOperations.getTarget(SLinkOperations.getTarget(thisNode, "state", false), "structure", true), "virtual_getStatechart_1955678301119453888", new Object[]{}))
      );
    }
  }

  public static boolean virtual_isEndPoint_1955678301119752454(SNode thisNode) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(thisNode, "state", false), "structure", true) == null;
  }
}
