package statechart.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.SNode;

public abstract class TargetRefExpression_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public TargetRefExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "statechart.structure.TargetRefExpression";
  }

  public abstract Scope virtual_getTargetRefScope_3233011721676204377(SNode thisNode, SNode kind, SNode child);

  public abstract SNode virtual_getEndPointState_2164628666946425581(SNode thisNode);

  public abstract boolean virtual_isEndPoint_2164628666946456298(SNode thisNode);
}
