package statechart.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class True_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IPureExpression_BehaviorDescriptor {
  public True_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "statechart.structure.True";
  }
}
