package statechart.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;

public class Transition_Constraints extends BaseConstraintsDescriptor {
  public Transition_Constraints() {
    super("statechart.structure.Transition");
  }
}
