package statechart.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import statechart.behavior.TargetRefExpression_Behavior;
import statechart.behavior.Statechart_Behavior;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import jetbrains.mps.smodel.SModelUtil_new;

public class checkTargetReference_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public checkTargetReference_NonTypesystemRule() {
  }

  public void applyRule(final SNode nodeToCheck, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    if (!(SNodeOperations.hasRole(nodeToCheck, "statechart.structure.TargetRefDotExpression", "left")) && SLinkOperations.getTarget(SLinkOperations.getTarget(nodeToCheck, "state", false), "structure", true) != null && BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), SLinkOperations.getTarget(SLinkOperations.getTarget(nodeToCheck, "state", false), "structure", true), "virtual_getStatechart_1955678301119453888", new Object[]{}) != null) {
      if (TargetRefExpression_Behavior.call_toFinal_2747754268221296052(nodeToCheck)) {
        if (!(Statechart_Behavior.call_singleFinal_2747754268221309910(BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), SLinkOperations.getTarget(SLinkOperations.getTarget(nodeToCheck, "state", false), "structure", true), "virtual_getStatechart_1955678301119453888", new Object[]{})) != null)) {
          MessageTarget errorTarget = new NodeMessageTarget();
          IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(nodeToCheck, "undefined 'from' point", "r:e6b49452-7c70-4713-9029-6c9dda75fe0a(statechart.typesystem)", "7385576573235331892", null, errorTarget);
        }
      } else {
        if (!(Statechart_Behavior.call_singleInitial_2747754268221309514(BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), SLinkOperations.getTarget(SLinkOperations.getTarget(nodeToCheck, "state", false), "structure", true), "virtual_getStatechart_1955678301119453888", new Object[]{})) != null)) {
          MessageTarget errorTarget = new NodeMessageTarget();
          IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(nodeToCheck, "undefined 'to' point", "r:e6b49452-7c70-4713-9029-6c9dda75fe0a(statechart.typesystem)", "7385576573235442250", null, errorTarget);
        }
      }
    }
  }

  public String getApplicableConceptFQName() {
    return "statechart.structure.TargetReference";
  }

  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    {
      boolean b = SModelUtil_new.isAssignableConcept(argument.getConcept().getConceptId(), this.getApplicableConceptFQName());
      return new IsApplicableStatus(b, null);
    }
  }

  public boolean overrides() {
    return false;
  }
}
