package statechart.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import statechart.behavior.TargetReference_Behavior;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import statechart.behavior.Statechart_Behavior;
import jetbrains.mps.smodel.SModelUtil_new;

public class check_TargetReference_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public check_TargetReference_NonTypesystemRule() {
  }

  public void applyRule(final SNode nodeToCheck, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    if (SLinkOperations.getTarget(nodeToCheck, "next", true) != null && TargetReference_Behavior.call_toFinal_2747754268221296052(nodeToCheck)) {
      if (!(SPropertyOperations.getBoolean(SLinkOperations.getTarget(SLinkOperations.getTarget(nodeToCheck, "next", true), "state", false), "isFinal"))) {
        MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(SLinkOperations.getTarget(nodeToCheck, "next", true), "'from' field may reference only to final state", "r:e6b49452-7c70-4713-9029-6c9dda75fe0a(statechart.typesystem)", "2747754268221305026", null, errorTarget);
      }
    }
    if (SLinkOperations.getTarget(nodeToCheck, "next", true) != null && TargetReference_Behavior.call_toInitial_2747754268221296760(nodeToCheck)) {
      if (!(SPropertyOperations.getBoolean(SLinkOperations.getTarget(SLinkOperations.getTarget(nodeToCheck, "next", true), "state", false), "isInitial"))) {
        MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(SLinkOperations.getTarget(nodeToCheck, "next", true), "'to' field may reference only to initial state", "r:e6b49452-7c70-4713-9029-6c9dda75fe0a(statechart.typesystem)", "2747754268221305242", null, errorTarget);
      }
    }
    if (SLinkOperations.getTarget(nodeToCheck, "next", true) == null && SLinkOperations.getTarget(SLinkOperations.getTarget(nodeToCheck, "state", false), "structure", true) != null) {
      if (!(!(TargetReference_Behavior.call_toFinal_2747754268221296052(nodeToCheck)) || Statechart_Behavior.call_singleFinal_2747754268221309910(SLinkOperations.getTarget(SLinkOperations.getTarget(nodeToCheck, "state", false), "structure", true)) != null)) {
        MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(nodeToCheck, "undefined 'from' point", "r:e6b49452-7c70-4713-9029-6c9dda75fe0a(statechart.typesystem)", "2747754268221310260", null, errorTarget);
      }
      if (!(!(TargetReference_Behavior.call_toInitial_2747754268221296760(nodeToCheck)) || Statechart_Behavior.call_singleInitial_2747754268221309514(SLinkOperations.getTarget(SLinkOperations.getTarget(nodeToCheck, "state", false), "structure", true)) != null)) {
        MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(nodeToCheck, "undefined 'to' point", "r:e6b49452-7c70-4713-9029-6c9dda75fe0a(statechart.typesystem)", "2747754268221310395", null, errorTarget);
      }
    }
  }

  public String getApplicableConceptFQName() {
    return "statechart.structure.TargetReference";
  }

  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    {
      boolean b = SModelUtil_new.isAssignableConcept(argument.getConceptFqName(), this.getApplicableConceptFQName());
      return new IsApplicableStatus(b, null);
    }
  }

  public boolean overrides() {
    return false;
  }
}
