package statechart.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Statechart_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("19abcaab-5b93-450a-98af-c06bd2c1c087(statechart)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
