package statechart.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.nodeEditor.cells.EditorCell;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;

public class True_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_hpzb8f_a(editorContext, node);
  }

  private EditorCell createCollection_hpzb8f_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_hpzb8f_a");
    editorCell.addEditorCell(this.createConstant_hpzb8f_a0(editorContext, node));
    return editorCell;
  }

  private EditorCell createConstant_hpzb8f_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "true");
    editorCell.setCellId("Constant_hpzb8f_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }
}
