package statechart.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.generator.template.BaseMappingRuleContext;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import org.jetbrains.mps.openapi.model.SNode;

public class QueriesGenerated {
  public static boolean baseMappingRule_Condition_2747754268221229806(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return !(BehaviorReflection.invokeVirtual(Boolean.TYPE, SLinkOperations.getTarget(_context.getNode(), "from", true), "virtual_isEndPoint_1955678301119752454", new Object[]{})) || !(BehaviorReflection.invokeVirtual(Boolean.TYPE, SLinkOperations.getTarget(_context.getNode(), "to", true), "virtual_isEndPoint_1955678301119752454", new Object[]{}));
  }

  public static boolean baseMappingRule_Condition_2747754268221230799(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "states", true)).any(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SLinkOperations.getTarget(it, "structure", true) != null;
      }
    });
  }
}
