package smv.structure;

/*Generated by MPS */

import org.jetbrains.mps.openapi.module.SModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Smv_Language {
  public static SModuleReference MODULE_REFERENCE = jetbrains.mps.project.structure.modules.jetbrains.mps.project.structure.modules.ModuleReference.fromString("3d78b626-9ef8-499b-9c87-0c2eca515a31(smv)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
